# Pivot table

Using the data from the  **product_prices_cleaned.csv** file do the following:

1. create a pivot table so that the rows hold years, and columns have names of goods. Use the average price of the product as the value,
1. using `lambda` and `pivot_table`, recreate the view of the data discussed during the lecture. Analyse the result of the recreation, what can you say about what was passed to the function?
1. using `pivot_table`, see how the mean and median prices in the product groups were shaped across years (many functions can be passed as a list).

Subsection 2 hint:

Code from the lecture:
```
pd.pivot(data=df, index=['province', 'product'], columns=['date'], values=['value'])
```

In [25]:
import pandas as pd

path = r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_cleaned_2.csv'

df = pd.read_csv(path, sep=';', encoding='UTF-8', decimal='.')
df.describe()

,product_group_id,value,month,year,quarter
count,132251.000000,123683.000000,132251.000000,132251.000000,132251.000000
mean,2.380443,7.226827,6.501652,2008.995977,2.500533
std,0.935575,35.857858,3.451929,6.054866,1.118055
min,1.000000,0.000000,1.000000,1999.000000,1.000000
25%,2.000000,0.000000,4.000000,2004.000000,2.000000
50%,2.000000,3.900000,7.000000,2009.000000,3.000000
75%,3.000000,11.840000,10.000000,2014.000000,4.000000
max,4.000000,3000.000000,12.000000,2019.000000,4.000000

In [28]:
df_wo_duplicates = df.drop_duplicates(subset=['province','product','date'])

In [30]:
pd.pivot(
    data = df_wo_duplicates,
    index=['province', 'product'],
    columns=['date'],
    values=['value']
)

# Radimo samo transpoze, menjamo kolone i redove radi lakseg koriscenja za report (po potrebi)

                                                         value             \
date                                                       NaN 1999-01-01
province       product
NaN            NaN                                         NaN        NaN
GREATER POLAND 30% tomato concentrate - per 1kg            NaN       7.56
               Backpacker's canned pork meat - per 300 g   NaN       2.92
               Hunter's sausage dried - per 1kg            NaN      15.50
               Italian head cheese - per 1kg               NaN       6.14
...                                                        ...        ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg    NaN       8.07
               salted herring, non-dressed - per 1kg       NaN       0.00
               smoked bacon with ribs - per 1kg            NaN       8.01
               white table salt bagged - per 1kg           NaN       0.00
               whole pickled cucumbers 0.9l - per 1pc.     NaN       0.00

                                                                     \
date                                                     1999-02-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                7.09
               Backpacker's canned pork meat - per 300 g       2.88
               Hunter's sausage dried - per 1kg               16.31
               Italian head cheese - per 1kg                   5.78
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        8.62
               salted herring, non-dressed - per 1kg           0.00
               smoked bacon with ribs - per 1kg                8.93
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         0.00

                                                                     \
date                                                     1999-03-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                7.32
               Backpacker's canned pork meat - per 300 g       2.92
               Hunter's sausage dried - per 1kg               15.91
               Italian head cheese - per 1kg                   5.84
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        8.39
               salted herring, non-dressed - per 1kg           0.00
               smoked bacon with ribs - per 1kg                9.01
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         0.00

                                                                     \
date                                                     1999-04-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                7.84
               Backpacker's canned pork meat - per 300 g       2.85
               Hunter's sausage dried - per 1kg               15.80
               Italian head cheese - per 1kg                   6.00
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        8.28
               salted herring, non-dressed - per 1kg           0.00
               smoked bacon with ribs - per 1kg                8.12
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         0.00

                                                                     \
date                                                     1999-05-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                6.84
               Backpacker's canned pork meat - per 300 g       2.81
               Hunter's sausage dried - per 1kg               15.52
               Italian head cheese - per 1kg                   5.97
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        8.29
               salted herring, non-dressed - per 1kg           0.00
               smoked bacon with ribs - per 1kg                8.74
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         0.00

                                                                     \
date                                                     1999-06-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                7.41
               Backpacker's canned pork meat - per 300 g       3.05
               Hunter's sausage dried - per 1kg               16.49
               Italian head cheese - per 1kg                   6.07
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        8.49
               salted herring, non-dressed - per 1kg           0.00
               smoked bacon with ribs - per 1kg                8.36
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         0.00

                                                                     \
date                                                     1999-07-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                7.28
               Backpacker's canned pork meat - per 300 g       3.20
               Hunter's sausage dried - per 1kg               15.92
               Italian head cheese - per 1kg                   6.02
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        8.21
               salted herring, non-dressed - per 1kg           0.00
               smoked bacon with ribs - per 1kg                8.91
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         0.00

                                                                     \
date                                                     1999-08-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                8.27
               Backpacker's canned pork meat - per 300 g       3.06
               Hunter's sausage dried - per 1kg               16.27
               Italian head cheese - per 1kg                   6.02
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        8.64
               salted herring, non-dressed - per 1kg           0.00
               smoked bacon with ribs - per 1kg                8.98
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         0.00

                                                                     ...  \
date                                                     1999-09-01  ...
province       product                                               ...
NaN            NaN                                              NaN  ...
GREATER POLAND 30% tomato concentrate - per 1kg                7.23  ...
               Backpacker's canned pork meat - per 300 g       2.76  ...
               Hunter's sausage dried - per 1kg               16.27  ...
               Italian head cheese - per 1kg                   6.33  ...
...                                                             ...  ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        8.44  ...
               salted herring, non-dressed - per 1kg           0.00  ...
               smoked bacon with ribs - per 1kg                8.23  ...
               white table salt bagged - per 1kg               0.00  ...
               whole pickled cucumbers 0.9l - per 1pc.         0.00  ...

                                                                     \
date                                                     2019-03-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                6.78
               Backpacker's canned pork meat - per 300 g       2.97
               Hunter's sausage dried - per 1kg               21.59
               Italian head cheese - per 1kg                  10.13
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       10.24
               salted herring, non-dressed - per 1kg           5.32
               smoked bacon with ribs - per 1kg               16.80
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         2.25

                                                                     \
date                                                     2019-04-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                5.67
               Backpacker's canned pork meat - per 300 g       2.24
               Hunter's sausage dried - per 1kg               17.41
               Italian head cheese - per 1kg                   5.56
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       10.57
               salted herring, non-dressed - per 1kg           5.28
               smoked bacon with ribs - per 1kg               14.94
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         2.29

                                                                     \
date                                                     2019-05-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                1.14
               Backpacker's canned pork meat - per 300 g       2.50
               Hunter's sausage dried - per 1kg               21.49
               Italian head cheese - per 1kg                   8.75
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       10.52
               salted herring, non-dressed - per 1kg           6.99
               smoked bacon with ribs - per 1kg               12.34
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         2.33

                                                                     \
date                                                     2019-06-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                3.69
               Backpacker's canned pork meat - per 300 g       3.06
               Hunter's sausage dried - per 1kg               17.95
               Italian head cheese - per 1kg                   7.90
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        8.79
               salted herring, non-dressed - per 1kg           4.91
               smoked bacon with ribs - per 1kg                7.98
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         3.32

                                                                     \
date                                                     2019-07-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                9.71
               Backpacker's canned pork meat - per 300 g       2.67
               Hunter's sausage dried - per 1kg               19.25
               Italian head cheese - per 1kg                   9.52
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        9.99
               salted herring, non-dressed - per 1kg           5.94
               smoked bacon with ribs - per 1kg                7.38
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         2.46

                                                                     \
date                                                     2019-08-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                5.78
               Backpacker's canned pork meat - per 300 g       3.25
               Hunter's sausage dried - per 1kg               19.69
               Italian head cheese - per 1kg                   7.97
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        9.28
               salted herring, non-dressed - per 1kg           4.98
               smoked bacon with ribs - per 1kg                7.16
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         2.73

                                                                     \
date                                                     2019-09-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                4.96
               Backpacker's canned pork meat - per 300 g       2.54
               Hunter's sausage dried - per 1kg               19.45
               Italian head cheese - per 1kg                   7.56
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       11.14
               salted herring, non-dressed - per 1kg           7.18
               smoked bacon with ribs - per 1kg                7.71
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         2.67

                                                                     \
date                                                     2019-10-01
province       product
NaN            NaN                                              NaN
GREATER POLAND 30% tomato concentrate - per 1kg                6.12
               Backpacker's canned pork meat - per 300 g       3.26
               Hunter's sausage dried - per 1kg               22.95
               Italian head cheese - per 1kg                   9.28
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       10.49
               salted herring, non-dressed - per 1kg           5.36
               smoked bacon with ribs - per 1kg               14.79
               white table salt bagged - per 1kg               0.00
               whole pickled cucumbers 0.9l - per 1pc.         2.44


date                                                     2019-11-01 2019-12-01
province       product
NaN            NaN                                              NaN        NaN
GREATER POLAND 30% tomato concentrate - per 1kg                8.33       6.03
               Backpacker's canned pork meat - per 300 g       2.57       2.87
               Hunter's sausage dried - per 1kg               18.12      20.48
               Italian head cheese - per 1kg                   8.94      10.67
...                                                             ...        ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        9.39       9.67
               salted herring, non-dressed - per 1kg           5.25       7.32
               smoked bacon with ribs - per 1kg                7.96       7.67
               white table salt bagged - per 1kg               0.00       0.00
               whole pickled cucumbers 0.9l - per 1pc.         2.31       2.34

[511 rows x 253 columns]

In [36]:
pd.pivot_table(
    data = df,
    index=['province', 'product'],
    columns=['date'],
    values=['value'],
    aggfunc=lambda x: x+(x*0.2)
)

# sa pivot tabelom mozemo da aggregiramo zeljene kolone (cena) isto dobijamo transpose, ovde smeju da postoje duplikati, bice agregirani
# u agg mozemo stavljati i lambda funkcije, ovde je dodato da racuna cenu sa pdv

                                                              value  \
date                                                     1999-01-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               9.072
               Backpacker's canned pork meat - per 300 g      3.504
               Hunter's sausage dried - per 1kg                18.6
               Italian head cheese - per 1kg                  7.368
               Masurian barley groats - per 1kg                 0.0
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       9.684
               salted herring, non-dressed - per 1kg            0.0
               smoked bacon with ribs - per 1kg               9.612
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.          0.0

                                                                     \
date                                                     1999-02-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               8.508
               Backpacker's canned pork meat - per 300 g      3.456
               Hunter's sausage dried - per 1kg              19.572
               Italian head cheese - per 1kg                  6.936
               Masurian barley groats - per 1kg                 0.0
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg      10.344
               salted herring, non-dressed - per 1kg            0.0
               smoked bacon with ribs - per 1kg              10.716
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.          0.0

                                                                     \
date                                                     1999-03-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               8.784
               Backpacker's canned pork meat - per 300 g      3.504
               Hunter's sausage dried - per 1kg              19.092
               Italian head cheese - per 1kg                  7.008
               Masurian barley groats - per 1kg                 0.0
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg      10.068
               salted herring, non-dressed - per 1kg            0.0
               smoked bacon with ribs - per 1kg              10.812
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.          0.0

                                                                     \
date                                                     1999-04-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               9.408
               Backpacker's canned pork meat - per 300 g       3.42
               Hunter's sausage dried - per 1kg               18.96
               Italian head cheese - per 1kg                    7.2
               Masurian barley groats - per 1kg                 0.0
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       9.936
               salted herring, non-dressed - per 1kg            0.0
               smoked bacon with ribs - per 1kg               9.744
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.          0.0

                                                                     \
date                                                     1999-05-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               8.208
               Backpacker's canned pork meat - per 300 g      3.372
               Hunter's sausage dried - per 1kg              18.624
               Italian head cheese - per 1kg                  7.164
               Masurian barley groats - per 1kg                 0.0
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       9.948
               salted herring, non-dressed - per 1kg            0.0
               smoked bacon with ribs - per 1kg              10.488
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.          0.0

                                                                     \
date                                                     1999-06-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               8.892
               Backpacker's canned pork meat - per 300 g       3.66
               Hunter's sausage dried - per 1kg              19.788
               Italian head cheese - per 1kg                  7.284
               Masurian barley groats - per 1kg                 0.0
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg      10.188
               salted herring, non-dressed - per 1kg            0.0
               smoked bacon with ribs - per 1kg              10.032
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.          0.0

                                                                     \
date                                                     1999-07-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               8.736
               Backpacker's canned pork meat - per 300 g       3.84
               Hunter's sausage dried - per 1kg              19.104
               Italian head cheese - per 1kg                  7.224
               Masurian barley groats - per 1kg                 0.0
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       9.852
               salted herring, non-dressed - per 1kg            0.0
               smoked bacon with ribs - per 1kg              10.692
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.          0.0

                                                                     \
date                                                     1999-08-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               9.924
               Backpacker's canned pork meat - per 300 g      3.672
               Hunter's sausage dried - per 1kg              19.524
               Italian head cheese - per 1kg                  7.224
               Masurian barley groats - per 1kg                 0.0
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg      10.368
               salted herring, non-dressed - per 1kg            0.0
               smoked bacon with ribs - per 1kg              10.776
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.          0.0

                                                                      \
date                                                      1999-09-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg                8.676
               Backpacker's canned pork meat - per 300 g       3.312
               Hunter's sausage dried - per 1kg               19.524
               Italian head cheese - per 1kg                   7.596
               Masurian barley groats - per 1kg           [0.0, 0.0]
...                                                              ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg       10.128
               salted herring, non-dressed - per 1kg             0.0
               smoked bacon with ribs - per 1kg                9.876
               white table salt bagged - per 1kg                 0.0
               whole pickled cucumbers 0.9l - per 1pc.           0.0

                                                                      ...  \
date                                                      1999-10-01  ...
province       product                                                ...
GREATER POLAND 30% tomato concentrate - per 1kg                8.424  ...
               Backpacker's canned pork meat - per 300 g       3.696  ...
               Hunter's sausage dried - per 1kg               19.704  ...
               Italian head cheese - per 1kg                   6.804  ...
               Masurian barley groats - per 1kg           [0.0, 0.0]  ...
...                                                              ...  ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg        9.732  ...
               salted herring, non-dressed - per 1kg             0.0  ...
               smoked bacon with ribs - per 1kg               10.728  ...
               white table salt bagged - per 1kg                 0.0  ...
               whole pickled cucumbers 0.9l - per 1pc.           0.0  ...

                                                                          \
date                                                          2019-03-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg                    8.136
               Backpacker's canned pork meat - per 300 g           3.564
               Hunter's sausage dried - per 1kg                   25.908
               Italian head cheese - per 1kg                      12.156
               Masurian barley groats - per 1kg           [2.928, 2.928]
...                                                                  ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg           12.288
               salted herring, non-dressed - per 1kg               6.384
               smoked bacon with ribs - per 1kg                    20.16
               white table salt bagged - per 1kg                     0.0
               whole pickled cucumbers 0.9l - per 1pc.               2.7

                                                                     \
date                                                     2019-04-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               6.804
               Backpacker's canned pork meat - per 300 g      2.688
               Hunter's sausage dried - per 1kg              20.892
               Italian head cheese - per 1kg                  6.672
               Masurian barley groats - per 1kg               1.884
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg      12.684
               salted herring, non-dressed - per 1kg          6.336
               smoked bacon with ribs - per 1kg              17.928
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.        2.748

                                                                          \
date                                                          2019-05-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg                    1.368
               Backpacker's canned pork meat - per 300 g             3.0
               Hunter's sausage dried - per 1kg                   25.788
               Italian head cheese - per 1kg                        10.5
               Masurian barley groats - per 1kg           [4.308, 4.308]
...                                                                  ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg           12.624
               salted herring, non-dressed - per 1kg               8.388
               smoked bacon with ribs - per 1kg                   14.808
               white table salt bagged - per 1kg                     0.0
               whole pickled cucumbers 0.9l - per 1pc.             2.796

                                                                     \
date                                                     2019-06-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               4.428
               Backpacker's canned pork meat - per 300 g      3.672
               Hunter's sausage dried - per 1kg               21.54
               Italian head cheese - per 1kg                   9.48
               Masurian barley groats - per 1kg               2.796
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg      10.548
               salted herring, non-dressed - per 1kg          5.892
               smoked bacon with ribs - per 1kg               9.576
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.        3.984

                                                                                                    \
date                                                                                    2019-07-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg                                             11.652
               Backpacker's canned pork meat - per 300 g                                     3.204
               Hunter's sausage dried - per 1kg                                               23.1
               Italian head cheese - per 1kg                                                11.424
               Masurian barley groats - per 1kg           [2.8680000000000003, 2.8680000000000003]
...                                                                                            ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg                                     11.988
               salted herring, non-dressed - per 1kg                                         7.128
               smoked bacon with ribs - per 1kg                                              8.856
               white table salt bagged - per 1kg                                               0.0
               whole pickled cucumbers 0.9l - per 1pc.                                       2.952

                                                                     \
date                                                     2019-08-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               6.936
               Backpacker's canned pork meat - per 300 g        3.9
               Hunter's sausage dried - per 1kg              23.628
               Italian head cheese - per 1kg                  9.564
               Masurian barley groats - per 1kg               2.208
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg      11.136
               salted herring, non-dressed - per 1kg          5.976
               smoked bacon with ribs - per 1kg               8.592
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.        3.276

                                                                     \
date                                                     2019-09-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               5.952
               Backpacker's canned pork meat - per 300 g      3.048
               Hunter's sausage dried - per 1kg               23.34
               Italian head cheese - per 1kg                  9.072
               Masurian barley groats - per 1kg               2.352
...                                                             ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg      13.368
               salted herring, non-dressed - per 1kg          8.616
               smoked bacon with ribs - per 1kg               9.252
               white table salt bagged - per 1kg                0.0
               whole pickled cucumbers 0.9l - per 1pc.        3.204

                                                                          \
date                                                          2019-10-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg                    7.344
               Backpacker's canned pork meat - per 300 g           3.912
               Hunter's sausage dried - per 1kg                    27.54
               Italian head cheese - per 1kg                      11.136
               Masurian barley groats - per 1kg           [1.428, 1.428]
...                                                                  ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg           12.588
               salted herring, non-dressed - per 1kg               6.432
               smoked bacon with ribs - per 1kg                   17.748
               white table salt bagged - per 1kg                     0.0
               whole pickled cucumbers 0.9l - per 1pc.             2.928


date                                                     2019-11-01 2019-12-01
province       product
GREATER POLAND 30% tomato concentrate - per 1kg               9.996      7.236
               Backpacker's canned pork meat - per 300 g      3.084      3.444
               Hunter's sausage dried - per 1kg              21.744     24.576
               Italian head cheese - per 1kg                 10.728     12.804
               Masurian barley groats - per 1kg               1.872        3.9
...                                                             ...        ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg      11.268     11.604
               salted herring, non-dressed - per 1kg            6.3      8.784
               smoked bacon with ribs - per 1kg               9.552      9.204
               white table salt bagged - per 1kg                0.0        0.0
               whole pickled cucumbers 0.9l - per 1pc.        2.772      2.808

[510 rows x 252 columns]