# Aggregation


Using data from file **product_prices_cleaned.csv**, aggregate the data for each product by month and determine the statistics: `min, max, median, mean, std` for prices (**value** column):

1. skip the national data in the analysis,
1. directly on the object from `groupby`,
1. write a loop that will calculate these values for individual provinces.

Use the `agg` method, and aggregate the data with the `'product','date'` column to complete the exercise.

In [135]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_cleaned_2.csv',
    sep=';',
    encoding='UTF-8',
    decimal='.'
)
df

C:\Users\UrosVukmanovic\AppData\Local\Temp\ipykernel_32904\455173916.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,province,product_types,currency,product_group_id,product_line,value,date,product
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2,bread - per 1kg
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg
...,...,...,...,...,...,...,...,...
132247,KUYAVIA-POMERANIA,NaN,PLN,2.0,pork meat (raw bacon) - per 1kg,12.15,2016-11,pork meat (raw bacon) - per 1kg
132248,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3.0,NaN,0.0,2012-5,"beet sugar white, bagged - per 1kg"
132249,LESSER POLAND,NaN,PLN,4.0,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6,plain mixed bread (wheat-rye) - per 1kg
132250,WARMIA-MASURIA,NaN,PLN,2.0,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg
132251,NaN,NaN,NaN,NaN,NaN,PLN,NaN,NaN

In [136]:
df_clean = df.loc[
    ~(df['province'] == 'POLSKA') &
    ~(df['province'] == 'POLAND') &
    (df['province'].notnull()) &
    ~(df['value'] == 0) &
    ~(df['value'] == 3000) &
    (df['value'].notnull())     
    ]

df_clean['province'].unique()

array(['SUBCARPATHIA', 'KUYAVIA-POMERANIA', 'LOWER SILESIA',
       'WARMIA-MASURIA', 'HOLY CROSS', 'PODLASKIE', 'POMERANIA',
       'LESSER POLAND', 'ŁÓDŹ', 'MASOVIA', 'GREATER POLAND', 'LUBLIN',
       'LUBUSZ', 'WEST POMERANIA', 'SILESIA', 'OPOLE'], dtype=object)

In [137]:
df_clean

,province,product_types,currency,product_group_id,product_line,value,date,product
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg
5,HOLY CROSS,whole pickled cucumbers 0.9l - per 1pc.,PLN,1.0,NaN,0.28,2010-4,whole pickled cucumbers 0.9l - per 1pc.
...,...,...,...,...,...,...,...,...
132246,SILESIA,NaN,PLN,2.0,barley groats sausage - per 1kg,4.5,2004-8,barley groats sausage - per 1kg
132247,KUYAVIA-POMERANIA,NaN,PLN,2.0,pork meat (raw bacon) - per 1kg,12.15,2016-11,pork meat (raw bacon) - per 1kg
132248,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3.0,NaN,0.0,2012-5,"beet sugar white, bagged - per 1kg"
132249,LESSER POLAND,NaN,PLN,4.0,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6,plain mixed bread (wheat-rye) - per 1kg
132250,WARMIA-MASURIA,NaN,PLN,2.0,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg

In [138]:
df_clean["value"] = pd.to_numeric(df["value"], errors="coerce")

C:\Users\UrosVukmanovic\AppData\Local\Temp\ipykernel_32904\1406081948.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["value"] = pd.to_numeric(df["value"], errors="coerce")

In [139]:
result = df_clean.groupby(by=['product','date'])['value'].agg(['min','max', 'mean', 'median', 'std'])
result

                                                  min   max      mean  median  \
product                                 date
30% tomato concentrate - per 1kg        1999-1   3.81  8.03  6.527500   6.740
                                        1999-10  1.27  7.46  5.840000   6.730
                                        1999-11  0.00  8.21  5.436667   6.550
                                        1999-12  0.95  7.87  5.706250   6.920
                                        1999-2   2.67  7.73  6.120000   7.000
...                                               ...   ...       ...     ...
whole pickled cucumbers 0.9l - per 1pc. 2019-5   0.06  4.83  2.534286   2.525
                                        2019-6   0.66  5.37  2.375000   1.925
                                        2019-7   0.03  3.76  1.997857   2.205
                                        2019-8   0.61  3.92  2.343571   2.160
                                        2019-9   0.38  3.96  2.361429   2.355

                                                      std
product                                 date
30% tomato concentrate - per 1kg        1999-1   1.280823
                                        1999-10  2.109191
                                        1999-11  2.936788
                                        1999-12  2.786359
                                        1999-2   1.799540
...                                                   ...
whole pickled cucumbers 0.9l - per 1pc. 2019-5   1.253885
                                        2019-6   1.285569
                                        2019-7   1.073092
                                        2019-8   1.067273
                                        2019-9   0.997673

[7012 rows x 5 columns]

In [155]:
result1 = df_clean.groupby(by=['province','product'])['value'].agg(['min','max', 'mean', 'median', 'std'])
result1

                                                            min    max  \
province       product
GREATER POLAND 30% tomato concentrate - per 1kg            1.14  15.59
               Backpacker's canned pork meat - per 300 g   0.03   3.26
               Hunter's sausage dried - per 1kg           15.12  24.11
               Italian head cheese - per 1kg               5.56  11.44
               Masurian barley groats - per 1kg            0.04   3.96
...                                                         ...    ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg    6.92  11.60
               salted herring, non-dressed - per 1kg       0.00   9.91
               smoked bacon with ribs - per 1kg            7.16  18.86
               white table salt bagged - per 1kg           0.00   0.00
               whole pickled cucumbers 0.9l - per 1pc.     0.24   3.44

                                                               mean  median  \
province       product
GREATER POLAND 30% tomato concentrate - per 1kg           10.357809  10.230
               Backpacker's canned pork meat - per 300 g   2.211912   2.170
               Hunter's sausage dried - per 1kg           19.209762  18.725
               Italian head cheese - per 1kg               8.272698   7.965
               Masurian barley groats - per 1kg            2.554013   3.020
...                                                             ...     ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg    9.073929   8.900
               salted herring, non-dressed - per 1kg       7.099000   7.390
               smoked bacon with ribs - per 1kg           13.132103  12.945
               white table salt bagged - per 1kg           0.000000   0.000
               whole pickled cucumbers 0.9l - per 1pc.     2.680788   2.760

                                                               std
province       product
GREATER POLAND 30% tomato concentrate - per 1kg           2.477641
               Backpacker's canned pork meat - per 300 g  0.526852
               Hunter's sausage dried - per 1kg           2.130595
               Italian head cheese - per 1kg              1.680842
               Masurian barley groats - per 1kg           1.156887
...                                                            ...
ŁÓDŹ           pork meat with bone (shoulder) - per 1kg   1.096899
               salted herring, non-dressed - per 1kg      2.307926
               smoked bacon with ribs - per 1kg           2.493109
               white table salt bagged - per 1kg               NaN
               whole pickled cucumbers 0.9l - per 1pc.    0.503797

[459 rows x 5 columns]

In [140]:
result.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7012 entries, ('30% tomato concentrate - per 1kg', '1999-1') to ('whole pickled cucumbers 0.9l - per 1pc.', '2019-9')
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   min     7012 non-null   float64
 1   max     7012 non-null   float64
 2   mean    7012 non-null   float64
 3   median  7012 non-null   float64
 4   std     7005 non-null   float64
dtypes: float64(5)
memory usage: 296.7+ KB