Sample preparation of data for Python model

Dataset

    In this article, we will work on a dataset that stores various parameters relating to the diagnosis of cancer cells, based on which it is decided whether the cancer is malignant or not.

Preparing data for the model
1. Reading the dataset

In [104]:
import pandas as pd
cancer_df = pd.read_csv("data/cancer_data_course.csv")

cancer_df.head(10)

,Unnamed: 0,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN
5,5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440,NaN
6,6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,NaN
7,7,84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510,NaN
8,8,844981,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,...,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720,NaN
9,9,84501001,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,...,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750,NaN

Checking dataset

In [105]:
cancer_df.describe

<bound method NDFrame.describe of      Unnamed: 0        id diagnosis  radius_mean  texture_mean  \
0             0    842302         M        17.99         10.38
1             1    842517         M        20.57         17.77
2             2  84300903         M        19.69         21.25
3             3  84348301         M        11.42         20.38
4             4  84358402         M        20.29         14.34
..          ...       ...       ...          ...           ...
564         564    926424         M        21.56         22.39
565         565    926682         M        20.13         28.25
566         566    926954         M        16.60         28.08
567         567    927241         M        20.60         29.33
568         568     92751         B         7.76         24.54

     perimeter_mean  area_mean  smoothness_mean  compactness_mean  \
0            122.80     1001.0          0.11840           0.27760
1            132.90     1326.0          0.08474           0.07864
2            130.00     1203.0          0.10960           0.15990
3             77.58      386.1          0.14250           0.28390
4            135.10     1297.0          0.10030           0.13280
..              ...        ...              ...               ...
564          142.00     1479.0          0.11100           0.11590
565          131.20     1261.0          0.09780           0.10340
566          108.30      858.1          0.08455           0.10230
567          140.10     1265.0          0.11780           0.27700
568           47.92      181.0          0.05263           0.04362

     concavity_mean  ...  texture_worst  perimeter_worst  area_worst  \
0           0.30010  ...          17.33           184.60      2019.0
1           0.08690  ...          23.41           158.80      1956.0
2           0.19740  ...          25.53           152.50      1709.0
3           0.24140  ...          26.50            98.87       567.7
4           0.19800  ...          16.67           152.20      1575.0
..              ...  ...            ...              ...         ...
564         0.24390  ...          26.40           166.10      2027.0
565         0.14400  ...          38.25           155.00      1731.0
566         0.09251  ...          34.12           126.70      1124.0
567         0.35140  ...          39.42           184.60      1821.0
568         0.00000  ...          30.37            59.16       268.6

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119
1             0.12380            0.18660           0.2416
2             0.14440            0.42450           0.4504
3             0.20980            0.86630           0.6869
4             0.13740            0.20500           0.4000
..                ...                ...              ...
564           0.14100            0.21130           0.4107
565           0.11660            0.19220           0.3215
566           0.11390            0.30940           0.3403
567           0.16500            0.86810           0.9387
568           0.08996            0.06444           0.0000

     concave points_worst  symmetry_worst  fractal_dimension_worst  \
0                  0.2654          0.4601                  0.11890
1                  0.1860          0.2750                  0.08902
2                  0.2430          0.3613                  0.08758
3                  0.2575          0.6638                  0.17300
4                  0.1625          0.2364                  0.07678
..                    ...             ...                      ...
564                0.2216          0.2060                  0.07115
565                0.1628          0.2572                  0.06637
566                0.1418          0.2218                  0.07820
567                0.2650          0.4087                  0.12400
568                0.0000          0.2871                  0.07039

     Unnamed: 32
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
..           ...
564          NaN
565          NaN
566          NaN
567          NaN
568          NaN

[569 rows x 34 columns]>

In [106]:
cancer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               569 non-null    int64
 1   id                       569 non-null    int64
 2   diagnosis                569 non-null    object
 3   radius_mean              567 non-null    float64
 4   texture_mean             562 non-null    float64
 5   perimeter_mean           568 non-null    float64
 6   area_mean                564 non-null    float64
 7   smoothness_mean          563 non-null    float64
 8   compactness_mean         568 non-null    float64
 9   concavity_mean           566 non-null    float64
 10  concave points_mean      567 non-null    float64
 11  symmetry_mean            564 non-null    float64
 12  fractal_dimension_mean   564 non-null    float64
 13  radius_se                565 non-null    float64
 14  texture_se               567 non-null    float64
 15  perimeter_se             565 non-null    float64
 16  area_se                  567 non-null    float64
 17  smoothness_se            567 non-null    float64
 18  compactness_se           562 non-null    float64
 19  concavity_se             567 non-null    float64
 20  concave points_se        560 non-null    float64
 21  symmetry_se              565 non-null    float64
 22  fractal_dimension_se     565 non-null    float64
 23  radius_worst             564 non-null    float64
 24  texture_worst            562 non-null    float64
 25  perimeter_worst          569 non-null    float64
 26  area_worst               568 non-null    float64
 27  smoothness_worst         566 non-null    float64
 28  compactness_worst        567 non-null    float64
 29  concavity_worst          569 non-null    float64
 30  concave points_worst     567 non-null    float64
 31  symmetry_worst           564 non-null    float64
 32  fractal_dimension_worst  564 non-null    float64
 33  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(2), object(1)
memory usage: 151.3+ KB

In [107]:
cancer_df.isnull().sum()

Unnamed: 0                   0
id                           0
diagnosis                    0
radius_mean                  2
texture_mean                 7
perimeter_mean               1
area_mean                    5
smoothness_mean              6
compactness_mean             1
concavity_mean               3
concave points_mean          2
symmetry_mean                5
fractal_dimension_mean       5
radius_se                    4
texture_se                   2
perimeter_se                 4
area_se                      2
smoothness_se                2
compactness_se               7
concavity_se                 2
concave points_se            9
symmetry_se                  4
fractal_dimension_se         4
radius_worst                 5
texture_worst                7
perimeter_worst              0
area_worst                   1
smoothness_worst             3
compactness_worst            2
concavity_worst              0
concave points_worst         2
symmetry_worst               5
fractal_dimension_worst      5
Unnamed: 32                569
dtype: int64

2. Removing redundant variables

In [108]:
cancer_df = cancer_df.drop(columns=["id", "Unnamed: 32", "Unnamed: 0"])
cancer_df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

3. Removing missing values

In [109]:
# Calculating the percentage of null values

missing_values = cancer_df.isnull().sum()/(len(cancer_df))*100
missing_values.round(2)

# Maximum missing_values_% is 1.58 - it's okay to delete observations with missing values

diagnosis                  0.00
radius_mean                0.35
texture_mean               1.23
perimeter_mean             0.18
area_mean                  0.88
smoothness_mean            1.05
compactness_mean           0.18
concavity_mean             0.53
concave points_mean        0.35
symmetry_mean              0.88
fractal_dimension_mean     0.88
radius_se                  0.70
texture_se                 0.35
perimeter_se               0.70
area_se                    0.35
smoothness_se              0.35
compactness_se             1.23
concavity_se               0.35
concave points_se          1.58
symmetry_se                0.70
fractal_dimension_se       0.70
radius_worst               0.88
texture_worst              1.23
perimeter_worst            0.00
area_worst                 0.18
smoothness_worst           0.53
compactness_worst          0.35
concavity_worst            0.00
concave points_worst       0.35
symmetry_worst             0.88
fractal_dimension_worst    0.88
dtype: float64

In [110]:
# Drop rows with at least 1 missing value

cancer_df = cancer_df.dropna(axis=0).reset_index()
cancer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549 entries, 0 to 548
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   index                    549 non-null    int64
 1   diagnosis                549 non-null    object
 2   radius_mean              549 non-null    float64
 3   texture_mean             549 non-null    float64
 4   perimeter_mean           549 non-null    float64
 5   area_mean                549 non-null    float64
 6   smoothness_mean          549 non-null    float64
 7   compactness_mean         549 non-null    float64
 8   concavity_mean           549 non-null    float64
 9   concave points_mean      549 non-null    float64
 10  symmetry_mean            549 non-null    float64
 11  fractal_dimension_mean   549 non-null    float64
 12  radius_se                549 non-null    float64
 13  texture_se               549 non-null    float64
 14  perimeter_se             549 non-null    float64
 15  area_se                  549 non-null    float64
 16  smoothness_se            549 non-null    float64
 17  compactness_se           549 non-null    float64
 18  concavity_se             549 non-null    float64
 19  concave points_se        549 non-null    float64
 20  symmetry_se              549 non-null    float64
 21  fractal_dimension_se     549 non-null    float64
 22  radius_worst             549 non-null    float64
 23  texture_worst            549 non-null    float64
 24  perimeter_worst          549 non-null    float64
 25  area_worst               549 non-null    float64
 26  smoothness_worst         549 non-null    float64
 27  compactness_worst        549 non-null    float64
 28  concavity_worst          549 non-null    float64
 29  concave points_worst     549 non-null    float64
 30  symmetry_worst           549 non-null    float64
 31  fractal_dimension_worst  549 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 137.4+ KB

Handling blank values

In [111]:
# Step 1: Create an imputer that fills missing numeric values with the mean of each column.
# This is a common strategy for numerical features before training a machine learning model.
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="mean")

# Step 2: Save the diagnosis column separately.
# We cannot fill missing values in a text column using the mean, so we remove it from the numeric data.
diagnosis_df = cancer_df["diagnosis"]

# Step 3: Remove the target column from the feature matrix and fill missing values.
# After this, cancer_df contains only the numeric feature columns with missing values replaced by averages.
cancer_df = imputer.fit_transform(cancer_df.drop("diagnosis", axis=1))

# Step 4: Convert the NumPy array returned by imputer back into a DataFrame.
# We restore the original column names so the data is easy to work with.
cancer_df = pd.DataFrame(cancer_df, columns=imputer.get_feature_names_out())

# Step 5: Add the diagnosis column back to the cleaned data.
# The extra index column created earlier is removed because it is not needed in the final dataset.
cancer_df = pd.concat([cancer_df, diagnosis_df], axis=1).drop("index", axis=1)

# Step 6: Remove the diagnosis column from the feature DataFrame.
# This final version keeps only the model inputs and removes the target label from the features.
cancer_df = cancer_df.drop(columns=["diagnosis"])

4. Removing duplicates

In [113]:
# Check if there are duplicated rows
cancer_df.duplicated().sum()

# no duplicates in the dataset

np.int64(0)