Statistics - exercise 2

Using the wine parameter dataset, which is available from the datasets module of the scikit-learn library, create a data frame for which you will calculate the indicated statistical measures. The dataset consists of 13 variables:

    alcohol - alcohol content of the wine (in percentage of volume).
    malic_acid - malic acid content in wine (in g / l).
    ash - the total amount of ash in the wine (in g / l).
    alcalinity_of_ash - degree of alcalinity of ash in wine (in mEq / l).
    magnesium - the content of magnesium in wine (in mg / l).
    total_phenols - the total amount of phenols in the wine (in mg / l).
    flavanoids - total amount of flavanoids in wine (in mg / l).
    nonflavanoid_phenols - total amount of non-flavonoid phenols in wine (in mg / l).
    proanthocyanins - total amount of proanthocyanins in wine (in mg / l).
    color_intensity - color intensity of the wine (in absorbance at 520 nm).
    hue - the hue of the wine, expressed in degrees.
    od280/od315_of_diluted wines - the ratio of wine absorbance at 280 nm to absorbance at 315 nm, a variable that determines color intensity.
    proline - the amount of proline in the wine (in mg / l).

1. For each variable in the wine_df frame, calculate the mean values and the median.
2. For the alcohol and malic_acid variables, determine the minimum value, maximum value and standard deviation.
3. For the variables total_phenoles and proline calculate the quantiles - first and third.
4. Calculate the correlation matrix, and then plot the results on a visualization made with the seaborn or plotly
5. library. Take care that the graph is appropriately sized so that the labels with correlation values are readable.

In [49]:
from sklearn.datasets import load_wine
import pandas as pd

wine_data = load_wine()
wine_df = pd.DataFrame(data=wine_data.data, columns=wine_data.feature_names)

In [50]:
wine_df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [51]:
df_wine_mean = wine_df.mean()
df_wine_mean

alcohol                          13.000618
malic_acid                        2.336348
ash                               2.366517
alcalinity_of_ash                19.494944
magnesium                        99.741573
total_phenols                     2.295112
flavanoids                        2.029270
nonflavanoid_phenols              0.361854
proanthocyanins                   1.590899
color_intensity                   5.058090
hue                               0.957449
od280/od315_of_diluted_wines      2.611685
proline                         746.893258
dtype: float64

In [52]:
max_values = wine_df[["alcohol", "malic_acid"]].max()
min_values = wine_df[["alcohol", "malic_acid"]].min()
std_dev = wine_df[["alcohol", "malic_acid"]].std()
print(f"Max values:\t{max_values}\n")
print(f"min:\t{min_values}\n")
print(f"Max values:\t{std_dev}")

Max values:	alcohol       14.83
malic_acid     5.80
dtype: float64

min:	alcohol       11.03
malic_acid     0.74
dtype: float64

Max values:	alcohol       0.811827
malic_acid    1.117146
dtype: float64

In [53]:
quartiles = wine_df[["total_phenols", "proline"]].quantile([0.25, 0.75])
quartiles

      total_phenols  proline
0.25         1.7425    500.5
0.75         2.8000    985.0

In [54]:
wine_df_correlation_matrix = wine_df.corr(method="pearson")
wine_df_correlation_matrix

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
alcohol,1.000000,0.094397,0.211545,-0.310235,0.270798,0.289101,0.236815,-0.155929,0.136698,0.546364,-0.071747,0.072343,0.643720
malic_acid,0.094397,1.000000,0.164045,0.288500,-0.054575,-0.335167,-0.411007,0.292977,-0.220746,0.248985,-0.561296,-0.368710,-0.192011
ash,0.211545,0.164045,1.000000,0.443367,0.286587,0.128980,0.115077,0.186230,0.009652,0.258887,-0.074667,0.003911,0.223626
alcalinity_of_ash,-0.310235,0.288500,0.443367,1.000000,-0.083333,-0.321113,-0.351370,0.361922,-0.197327,0.018732,-0.273955,-0.276769,-0.440597
magnesium,0.270798,-0.054575,0.286587,-0.083333,1.000000,0.214401,0.195784,-0.256294,0.236441,0.199950,0.055398,0.066004,0.393351
total_phenols,0.289101,-0.335167,0.128980,-0.321113,0.214401,1.000000,0.864564,-0.449935,0.612413,-0.055136,0.433681,0.699949,0.498115
flavanoids,0.236815,-0.411007,0.115077,-0.351370,0.195784,0.864564,1.000000,-0.537900,0.652692,-0.172379,0.543479,0.787194,0.494193
nonflavanoid_phenols,-0.155929,0.292977,0.186230,0.361922,-0.256294,-0.449935,-0.537900,1.000000,-0.365845,0.139057,-0.262640,-0.503270,-0.311385
proanthocyanins,0.136698,-0.220746,0.009652,-0.197327,0.236441,0.612413,0.652692,-0.365845,1.000000,-0.025250,0.295544,0.519067,0.330417
color_intensity,0.546364,0.248985,0.258887,0.018732,0.199950,-0.055136,-0.172379,0.139057,-0.025250,1.000000,-0.521813,-0.428815,0.316100
hue,-0.071747,-0.561296,-0.074667,-0.273955,0.055398,0.433681,0.543479,-0.262640,0.295544,-0.521813,1.000000,0.565468,0.236183
od280/od315_of_diluted_wines,0.072343,-0.368710,0.003911,-0.276769,0.066004,0.699949,0.787194,-0.503270,0.519067,-0.428815,0.565468,1.000000,0.312761
proline,0.643720,-0.192011,0.223626,-0.440597,0.393351,0.498115,0.494193,-0.311385,0.330417,0.316100,0.236183,0.312761,1.000000

In [58]:
import plotly.express as px
fig = px.imshow(
    wine_df_correlation_matrix,
    x = wine_df_correlation_matrix.columns,
    y = wine_df_correlation_matrix.index,
    title= "wine_df correlation matrix",
    width=700,
    height=700
)
fig.show()