# Merge with conditions

Using the raw data from the **product_prices_cleaned.csv** file, perform the task of finding out how many times a lower price has been quoted for a given product, province, month historically. To do this, perform the following steps:

1. merge the table with itself. What type of join should be used?
1. filter the data to find earlier years and the values smaller than the one from current year in a given province.
1. group the data accordingly.

Which product(s) had the most such occurrences?

> See what happens to the column names when the columns are not used as a merge condition, but have the same names

In [19]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_cleaned_2.csv',
    sep=';',
    encoding='UTF-8',
    decimal='.'
)
df.head()

C:\Users\UrosVukmanovic\AppData\Local\Temp\ipykernel_34532\486030517.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,province,product_types,currency,product_group_id,product_line,value,date,product
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2,bread - per 1kg
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg

In [20]:
df.loc[
    ~(df['province'] == 'POLSKA') &
    ~(df['province'] == 'POLAND') &
    (df['province'].notnull()) &
    ~(df['value'] == 0) &
    ~(df['value'] == 3000) &
    (df['value'].notnull())
    ]

,province,product_types,currency,product_group_id,product_line,value,date,product
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg
5,HOLY CROSS,whole pickled cucumbers 0.9l - per 1pc.,PLN,1.0,NaN,0.28,2010-4,whole pickled cucumbers 0.9l - per 1pc.
...,...,...,...,...,...,...,...,...
132246,SILESIA,NaN,PLN,2.0,barley groats sausage - per 1kg,4.5,2004-8,barley groats sausage - per 1kg
132247,KUYAVIA-POMERANIA,NaN,PLN,2.0,pork meat (raw bacon) - per 1kg,12.15,2016-11,pork meat (raw bacon) - per 1kg
132248,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3.0,NaN,0.0,2012-5,"beet sugar white, bagged - per 1kg"
132249,LESSER POLAND,NaN,PLN,4.0,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6,plain mixed bread (wheat-rye) - per 1kg
132250,WARMIA-MASURIA,NaN,PLN,2.0,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg

In [21]:
df["value"] = pd.to_numeric(df["value"], errors="coerce")

In [22]:
df_n = df[[
    'province',
    'value',
    'date',
    'product'
]]

In [23]:
df_self_join_province_prices = pd.merge(
    left=df_n,
    right=df_n,
    how='inner',
    on=['province', 'product']
)
df_self_join_province_prices

,province,value_x,date_x,product,value_y,date_y
0,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,21.37,2013-3
1,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,15.76,2007-1
2,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,20.88,2019-10
3,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,16.26,2010-4
4,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,17.52,2011-5
...,...,...,...,...,...,...
34471961,WARMIA-MASURIA,11.87,2000-11,boneless beef (sirloin) - per 1kg,26.49,2019-12
34471962,WARMIA-MASURIA,11.87,2000-11,boneless beef (sirloin) - per 1kg,20.33,2005-3
34471963,WARMIA-MASURIA,11.87,2000-11,boneless beef (sirloin) - per 1kg,19.56,2019-4
34471964,WARMIA-MASURIA,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.87,2000-11
34471965,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df_self_join_province_prices['date_x'].unique()

array(['2013-3', '2018-2', '2019-12', '2019-2', '2002-3', '2010-4',
       '2004-12', '2017-3', '1999-4', '2017-7', '2009-5', '2011-3',
       '1999-10', '2009-8', '2010-12', '2017-9', '2010-11', '2004-8',
       '2008-11', '1999-3', '2003-7', '2014-10', '2015-9', '2008-7',
       '2013-8', '2005-7', '2000-3', '2009-6', '2003-5', '2004-2',
       '2010-1', '2005-10', '2016-3', '2014-2', '2008-2', '2011-9',
       '2007-8', '2003-12', '2002-1', '2019-6', '2010-8', '2002-11',
       '2002-2', '2018-6', '2018-8', '2005-9', '2006-2', '2006-9',
       '2013-12', '2017-1', '2016-8', '2014-8', '2004-5', '2007-5',
       '2007-6', '2001-3', '2001-11', '2001-4', '2005-4', '2007-10',
       '2005-5', '2003-10', '2018-7', '2018-5', '2007-11', '2011-12',
       '2015-12', '2007-2', '2014-4', '2014-9', '2008-5', '2017-2',
       '2000-12', '2016-10', '2012-10', '2001-8', '2015-5', '2015-8',
       '2011-4', '2004-4', '2015-1', '2008-10', '2006-8', '2008-6',
       '2019-5', '2000-2', '2004-10', '2005-11', '2000-10', '1999-12',
       '2007-1', '2012-6', '2007-3', '2017-4', '2012-12', '2015-10',
       '1999-5', '2012-3', '2018-12', '2002-4', '2017-11', '2014-1',
       '2013-2', '2009-1', '1999-7', '2015-7', '1999-1', '2016-9',
       '2009-10', '2008-8', '2007-9', '2009-12', '2006-11', '2013-10',
       '2001-5', '2006-4', '2006-7', '2001-7', '2011-6', '2007-4',
       '2000-11', '2011-7', '2006-3', '2011-2', '2016-5', '2015-11',
       '2016-6', '2013-1', '2003-3', '2003-6', '2013-9', '2001-1',
       '2012-1', '2018-3', '2010-6', '2017-12', '2018-4', '2009-11',
       '2005-2', '2001-2', '2010-10', '2011-11', '2002-9', '2014-3',
       '2016-12', '2015-4', '2011-1', '2012-5', '2006-10', '2000-1',
       '2015-2', '2002-7', '2016-2', '1999-8', '2010-7', '2011-10',
       '2016-7', '2001-10', '2017-10', '2000-6', '2008-4', '2008-3',
       '2018-9', '2002-12', '2004-9', '2012-9', '2003-4', '2002-10',
       '2012-11', '2000-9', '2017-6', '1999-9', '2019-7', '2002-8',
       '2012-4', '2006-12', '2019-9', '1999-11', '2000-8', '2019-4',
       '2017-8', '2009-3', '2016-4', '2004-1', '2002-6', '2005-8',
       '2015-6', '2003-9', '2005-3', '2010-2', '2009-9', '2004-11',
       '2018-11', '2004-3', '2017-5', '2016-11', '2006-6', '2009-7',
       '2008-1', '2001-9', '2009-4', '2006-1', '2013-7', '2013-5',
       '2005-1', '1999-6', '2000-7', '2008-9', '2005-6', '2015-3',
       '2000-5', '2011-8', '2013-11', '2006-5', '2012-2', '2012-8',
       '2018-1', '2005-12', '2019-11', '2004-6', '2009-2', '2007-7',
       '2007-12', '2013-6', '2001-6', '2003-1', '2003-2', '2001-12',
       '2014-7', '2014-12', '2013-4', '2003-8', '2018-10', '2012-7',
       '2016-1', '2014-6', '2019-10', '2019-3', '2010-9', '2010-3',
       '2003-11', '2019-8', '2004-7', '2002-5', '1999-2', '2000-4',
       '2019-1', '2011-5', '2008-12', '2010-5', '2014-11', '2014-5', nan],
      dtype=object)

In [24]:
df_self_join_province_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34471966 entries, 0 to 34471965
Data columns (total 6 columns):
 #   Column    Dtype
---  ------    -----
 0   province  object
 1   value_x   float64
 2   date_x    object
 3   product   object
 4   value_y   float64
 5   date_y    object
dtypes: float64(2), object(4)
memory usage: 1.5+ GB

In [29]:
df_joined_filtered = df_self_join_province_prices.loc[
    (df_self_join_province_prices['value_x'] >= df_self_join_province_prices['value_y']) &
    (df_self_join_province_prices['date_x'] > df_self_join_province_prices['date_y'])
    ]
df_joined_filtered

,province,value_x,date_x,product,value_y,date_y
1,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,15.76,2007-1
3,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,16.26,2010-4
4,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,17.52,2011-5
5,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,15.57,2003-8
7,SUBCARPATHIA,21.37,2013-3,pork ham cooked - per 1kg,19.47,2012-1
...,...,...,...,...,...,...
34471855,WARMIA-MASURIA,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.58,1999-7
34471918,WARMIA-MASURIA,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.46,1999-8
34471926,WARMIA-MASURIA,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.49,1999-12
34471928,WARMIA-MASURIA,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.13,1999-9
34471946,WARMIA-MASURIA,11.87,2000-11,boneless beef (sirloin) - per 1kg,11.85,2000-10

In [31]:
df_joined_filtered.loc[
    df_joined_filtered['value_x'] > 0
].groupby(
    by=['province','product', 'date_x']
).size().sort_values(ascending=False)

province       product                                  date_x
SILESIA        Poznan wheat flour, bagged - per 1kg     2019-5     642
HOLY CROSS     Masurian barley groats - per 1kg         2019-9     612
LUBLIN         plain mixed bread (wheat-rye) - per 1kg  2019-8     612
OPOLE          Poznan wheat flour, bagged - per 1kg     2019-6     610
SILESIA        plain mixed bread (wheat-rye) - per 1kg  2019-6     610
                                                                  ...
LOWER SILESIA  pork ham cooked - per 1kg                1999-12      1
SILESIA        30% tomato concentrate - per 1kg         2001-11      1
PODLASKIE      boneless beef (sirloin) - per 1kg        1999-9       1
                                                        1999-7       1
SUBCARPATHIA   beef with bone (rump steak) - per 1kg    1999-7       1
Length: 85589, dtype: int64