# Highest and lowest price

Using `sort_values` and the data from the _product_prices_renamed.csv_ the file answer the questions below — use data aggregated for entire Poland (`province=='POLAND'`):

1. What product had the highest 'PLN' price in history? (remember to remove the value = 3000)?
1. What product achieved the lowest 'PLN' price in history? (remember to filter out values = 0),

Sort the data according to the following key:

1. by **product_types** column – descending
1. by **value** column – ascending

In [2]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_renamed.csv',
    sep=';',
    encoding='UTF-8',
    decimal='.'
)

print(df)

                 province                       product_types currency  \
0            SUBCARPATHIA                                 NaN      PLN
1                    ŁÓDŹ                                 NaN      PLN
2       KUYAVIA-POMERANIA                                 NaN      PLN
3           LOWER SILESIA                                 NaN      PLN
4          WARMIA-MASURIA                                 NaN      PLN
...                   ...                                 ...      ...
149935  KUYAVIA-POMERANIA                                 NaN      PLN
149936               ŁÓDŹ  beet sugar white, bagged - per 1kg      PLN
149937      LESSER POLAND                                 NaN      PLN
149938     WARMIA-MASURIA                                 NaN      PLN
149939            MASOVIA                                 NaN      PLN

        product_group_id                             product_line  value  \
0                      2                pork ham cooked - per 1kg  21.37
1                      4                          bread - per 1kg    NaN
2                      2          barley groats sausage - per 1kg   3.55
3                      2               dressed chickens - per 1kg   6.14
4                      2            Italian head cheese - per 1kg   5.63
...                  ...                                      ...    ...
149935                 2         pork  meat (raw bacon) - per 1kg  12.15
149936                 3                                      NaN   0.00
149937                 4  plain mixed bread (wheat-rye) - per 1kg   3.05
149938                 2        boneless beef (sirloin) - per 1kg  11.87
149939                 4         Masurian barley groats - per 1kg   0.16

           date
0        2013-3
1        2018-2
2       2019-12
3        2019-2
4        2002-3
...         ...
149935  2016-11
149936   2012-5
149937   2008-6
149938  2000-11
149939  2005-10

[149940 rows x 7 columns]

In [3]:
df.sort_values('value', ascending=False)

,province,product_types,currency,product_group_id,product_line,value,date
22321,WEST POMERANIA,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1
122007,LUBUSZ,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1
130871,HOLY CROSS,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1
104235,POLAND,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1
31268,SUBCARPATHIA,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1
...,...,...,...,...,...,...,...
149899,POLAND,NaN,PLN,4,bread - per 1kg,NaN,2016-10
149900,WARMIA-MASURIA,NaN,PLN,4,bread - per 1kg,NaN,2014-10
149911,SILESIA,NaN,PLN,2,fresh non-dressed carp - per 1kg,NaN,2018-8
149921,SUBCARPATHIA,NaN,PLN,2,fresh non-dressed trout - per 1kg,NaN,2002-5
149927,PODLASKIE,NaN,PLN,2,fresh non-dressed carp - per 1kg,NaN,2004-8

1. What product had the highest 'PLN' price in history? (remember to remove the value = 3000)?

In [27]:

df_province = df.loc[ 
    (df['province'] == 'POLAND')&
    (df['value']!=3000)& 
    (df['value']!= 0)
]

df_sorted_max = df_province.sort_values(by=['value'], ascending = False)
df_sorted_max.head(5)

,province,product_types,currency,product_group_id,product_line,value,date
104451,POLAND,NaN,PLN,2,boneless beef (sirloin) - per 1kg,31.90,2018-5
115089,POLAND,NaN,PLN,2,boneless beef (sirloin) - per 1kg,31.81,2017-10
78146,POLAND,NaN,PLN,2,boneless beef (sirloin) - per 1kg,31.71,2018-10
117199,POLAND,NaN,PLN,2,boneless beef (sirloin) - per 1kg,31.70,2017-9
121704,POLAND,NaN,PLN,2,boneless beef (sirloin) - per 1kg,31.61,2015-12

2. What product achieved the lowest 'PLN' price in history? (remember to filter out values = 0),

In [28]:
df_sorted_min = df_province.sort_values(by = ['value'], ascending = True)
df_sorted_min.head()

,province,product_types,currency,product_group_id,product_line,value,date
4910,POLAND,NaN,PLN,4,buckwheat groats roasted whole - per 1kg,0.02,2019-4
5282,POLAND,NaN,PLN,4,buckwheat groats roasted whole - per 1kg,0.02,2019-4
111812,POLAND,NaN,PLN,2,Backpacker's canned pork meat - per 300 g,0.09,2019-3
14851,POLAND,NaN,PLN,4,buckwheat groats roasted whole - per 1kg,0.17,2019-5
79905,POLAND,NaN,PLN,4,buckwheat groats roasted whole - per 1kg,0.17,2019-5

Sort the data according to the following key:

1. by **product_types** column – descending
1. by **value** column – ascending

In [ ]:
df.sort_values(
    by=['product_types', 'value'], 
    ascending=[False, True],
    na_position='last'
    )
df.head()

,province,product_types,currency,product_group_id,product_line,value,date
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3