# Filtering data
While generating the `product_prices_renamed.csv` file the following processing errors occurred and they need to be found:
1. In the **date** column, data from 1888 appeared - '1888-0',
2. Check the **date** column for similar errors but with future values.
3. In the **value** column, too high value was introduced – find it and locate the row where it is (use `query`),
4. There was a spelling error in the **product_types** column for one of the products. Find it and the corresponding rows. How many such rows are there?

You do not need to assign the results to the variable: it is enough if you display them.

> Based on the solution of this task, we will later correct all errors in the data.

Hints:

Subsection 2:
1. There is only one such value.
2. Use `loc` or `query` with the condition `date > '2020-1'`.

Subsection 3:
1. There is only one such value.
1. Do the following:
a) use `describe()`, to view percentiles,
b) use `loc` or `query` to find erroneous entries,

Subsection 4:

You can do it in the following way:
a) use `unique()` method to find all available values,
b) use `loc` or `query` to find erroneous entries,
c) The number of rows can be checked with the `shape` method.

In [2]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_renamed.csv',
    sep=';',
    encoding='UTF-8',
    decimal='.'
)

df_date_task1 = df.loc[df['date'] == '1888-0',]
df_date_task1.head()

,province,product_types,currency,product_group_id,product_line,value,date
11908,LUBUSZ,NaN,PLN,2,fresh non-dressed carp - per 1kg,8.17,1888-0
14765,SILESIA,NaN,PLN,2,fresh non-dressed carp - per 1kg,0.00,1888-0
16125,WARMIA-MASURIA,NaN,PLN,2,fresh non-dressed carp - per 1kg,8.03,1888-0
18737,LOWER SILESIA,NaN,PLN,2,fresh non-dressed carp - per 1kg,0.00,1888-0
20293,HOLY CROSS,NaN,PLN,2,fresh non-dressed carp - per 1kg,7.94,1888-0

In [4]:
df_date_task2 = df.loc[df['date'] > '2020-0',]
df_date_task2.head()

,province,product_types,currency,product_group_id,product_line,value,date
1583,HOLY CROSS,NaN,PLN,2,haddock fillets frozen - per 1kg,0.00,2099-13
35525,PODLASKIE,NaN,PLN,2,haddock fillets frozen - per 1kg,0.00,2099-13
43258,SILESIA,NaN,PLN,2,haddock fillets frozen - per 1kg,20.96,2099-13
52595,LUBUSZ,NaN,PLN,2,haddock fillets frozen - per 1kg,0.00,2099-13
56032,GREATER POLAND,NaN,PLN,2,haddock fillets frozen - per 1kg,18.92,2099-13

In [12]:
df_value_task_descr = df['value'].describe()
df_value_task_descr

count    137088.000000
mean          6.615227
std          34.112858
min           0.000000
25%           0.000000
50%           3.090000
75%          10.920000
max        3000.000000
Name: value, dtype: float64

In [4]:
df_value_task = df.query("value >= 3000")
df_value_task.head()

,province,product_types,currency,product_group_id,product_line,value,date
13724,POMERANIA,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1
18768,LOWER SILESIA,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1
22321,WEST POMERANIA,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1
31268,SUBCARPATHIA,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1
36958,LESSER POLAND,30% tomato concentrate - per 1kg,PLN,1,NaN,3000.0,2003-1

In [3]:
df_unique = df['product_types'].unique()

print(df_unique)

[nan 'whole pickled cucumbers 0.9l - per 1pc.'
 'fresh chichen egges - per 666pcs.' '30% tomato concentrate - per 1kg'
 'frozen carrot and pea mix - per 1kg'
 'beet sugar white, bagged - per 1kg' 'apple juice, boxed - per 1l'
 'white table salt bagged - per 1kg' 'natural chocolate plain - per 1kg']

In [5]:
df_typo = df[df['product_types'] == 'fresh chichen egges - per 666pcs.']

print(df_typo)

              province                      product_types currency  \
6       WEST POMERANIA  fresh chichen egges - per 666pcs.      PLN
13              POLAND  fresh chichen egges - per 666pcs.      PLN
38      WARMIA-MASURIA  fresh chichen egges - per 666pcs.      PLN
202     GREATER POLAND  fresh chichen egges - per 666pcs.      PLN
229     WARMIA-MASURIA  fresh chichen egges - per 666pcs.      PLN
...                ...                                ...      ...
149691       POMERANIA  fresh chichen egges - per 666pcs.      PLN
149718          LUBUSZ  fresh chichen egges - per 666pcs.      PLN
149724           OPOLE  fresh chichen egges - per 666pcs.      PLN
149767  WARMIA-MASURIA  fresh chichen egges - per 666pcs.      PLN
149838    SUBCARPATHIA  fresh chichen egges - per 666pcs.      PLN

        product_group_id product_line  value     date
6                      3          NaN   0.00  2004-12
13                     3          NaN   0.27   2009-8
38                     3          NaN   0.00  2003-12
202                    3          NaN   0.32   2018-8
229                    3          NaN   0.00   2013-1
...                  ...          ...    ...      ...
149691                 3          NaN   0.00   2019-3
149718                 3          NaN   0.00   2009-1
149724                 3          NaN   0.25  2011-12
149767                 3          NaN   0.00   2001-3
149838                 3          NaN   0.26   2019-4

[4284 rows x 7 columns]