## Selection of data for analysis

Answer the following questions:

1. What was the average price of a carrot and pea mix per 1 kg in Poland in 2015?
2. What was the average price of apple juice in 2016-2018 in the Masovia province?
3. What was the average price of tomato paste in Lower Silesia Province in 2003-2015? Compared with other products does it seem reasonable to you?<br>

Suggest what can be done with values equal to 0. How does this affect the results of point 3?

> All the product groups needed for this task are in the **product_types** column.

In [2]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_renamed.csv',
    sep=';',
    encoding='UTF-8',
    decimal='.'
)

print(df)

                 province                       product_types currency  \
0            SUBCARPATHIA                                 NaN      PLN
1                    ŁÓDŹ                                 NaN      PLN
2       KUYAVIA-POMERANIA                                 NaN      PLN
3           LOWER SILESIA                                 NaN      PLN
4          WARMIA-MASURIA                                 NaN      PLN
...                   ...                                 ...      ...
149935  KUYAVIA-POMERANIA                                 NaN      PLN
149936               ŁÓDŹ  beet sugar white, bagged - per 1kg      PLN
149937      LESSER POLAND                                 NaN      PLN
149938     WARMIA-MASURIA                                 NaN      PLN
149939            MASOVIA                                 NaN      PLN

        product_group_id                             product_line  value  \
0                      2                pork ham cooked - per 1kg  21.37
1                      4                          bread - per 1kg    NaN
2                      2          barley groats sausage - per 1kg   3.55
3                      2               dressed chickens - per 1kg   6.14
4                      2            Italian head cheese - per 1kg   5.63
...                  ...                                      ...    ...
149935                 2         pork  meat (raw bacon) - per 1kg  12.15
149936                 3                                      NaN   0.00
149937                 4  plain mixed bread (wheat-rye) - per 1kg   3.05
149938                 2        boneless beef (sirloin) - per 1kg  11.87
149939                 4         Masurian barley groats - per 1kg   0.16

           date
0        2013-3
1        2018-2
2       2019-12
3        2019-2
4        2002-3
...         ...
149935  2016-11
149936   2012-5
149937   2008-6
149938  2000-11
149939  2005-10

[149940 rows x 7 columns]

1. What was the average price of a carrot and pea mix per 1 kg in Poland in 2015?

In [28]:
df.describe()

       product_group_id          value
count     149940.000000  137088.000000
mean           2.571429       6.615227
std            1.022206      34.112858
min            1.000000       0.000000
25%            2.000000       0.000000
50%            2.000000       3.090000
75%            4.000000      10.920000
max            4.000000    3000.000000

In [4]:
df.head()

,province,product_types,currency,product_group_id,product_line,value,date
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3

In [5]:
df_unique = df['product_types'].unique()
print(df_unique)

[nan 'whole pickled cucumbers 0.9l - per 1pc.'
 'fresh chichen egges - per 666pcs.' '30% tomato concentrate - per 1kg'
 'frozen carrot and pea mix - per 1kg'
 'beet sugar white, bagged - per 1kg' 'apple juice, boxed - per 1l'
 'white table salt bagged - per 1kg' 'natural chocolate plain - per 1kg']

In [6]:
df.dtypes

province             object
product_types        object
currency             object
product_group_id      int64
product_line         object
value               float64
date                 object
dtype: object

In [11]:
df_price_carrot = df.loc[
    (df['product_types'] == 'frozen carrot and pea mix - per 1kg') &
    (df['province'] == 'POLAND') &
    (df['date'].str.startswith ('2015'))
]
df_price_carrot

,province,product_types,currency,product_group_id,product_line,value,date
8542,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.824096,2015-1
60491,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.843373,2015-12
64981,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.816867,2015-11
73561,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.792771,2015-4
113640,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.884337,2015-10
120465,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.766265,2015-6
125079,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.840964,2015-8
129550,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.843373,2015-7
132374,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.860241,2015-3
139865,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.874699,2015-5
139966,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.804819,2015-2
142825,POLAND,frozen carrot and pea mix - per 1kg,EUR,1,NaN,0.797590,2015-9

In [12]:
df_price_carrot['value'].mean()

np.float64(0.8291164658634539)

2. What was the average price of apple juice in 2016-2018 in the Masovia province?

In [55]:
df_price_apple = df.loc[
    (df['product_types'] == 'apple juice, boxed - per 1l') &
    (df['date'] >= '2016-1') &
    (df['date']<= '2018-1') &
    (df['province'] == 'MASOVIA')
]
df_price_apple.head()

,province,product_types,currency,product_group_id,product_line,value,date
9935,MASOVIA,"apple juice, boxed - per 1l",PLN,1,NaN,3.29,2017-3
11100,MASOVIA,"apple juice, boxed - per 1l",PLN,1,NaN,2.94,2016-5
18729,MASOVIA,"apple juice, boxed - per 1l",PLN,1,NaN,3.26,2017-10
24353,MASOVIA,"apple juice, boxed - per 1l",PLN,1,NaN,2.92,2016-10
26641,MASOVIA,"apple juice, boxed - per 1l",PLN,1,NaN,2.92,2017-4

In [56]:
df_price_apple['value'].mean()

np.float64(3.0515999999999996)

3. What was the average price of tomato paste in Lower Silesia Province in 2003-2015? Compared with other products does it seem reasonable to you?

In [ ]:
df_tomato_paste = df.loc[
    (df['product_types'] == '30% tomato concentrate - per 1kg') &
    (df['date'] >= '2003-1') &
    (df['date']<= '2015-1')
]
df_tomato_paste.head()

,province,product_types,currency,product_group_id,product_line,value,date
64,LOWER SILESIA,30% tomato concentrate - per 1kg,PLN,1,NaN,0.00,2007-10
77,HOLY CROSS,30% tomato concentrate - per 1kg,PLN,1,NaN,0.00,2007-2
92,KUYAVIA-POMERANIA,30% tomato concentrate - per 1kg,PLN,1,NaN,8.83,2010-1
159,HOLY CROSS,30% tomato concentrate - per 1kg,PLN,1,NaN,0.00,2011-6
191,HOLY CROSS,30% tomato concentrate - per 1kg,PLN,1,NaN,0.00,2012-3

In [51]:
df_tomato_paste['value'].mean()

np.float64(24.790421906693712)

In [52]:
df_tomato_paste2 = df.loc[
    (df['product_types'] == '30% tomato concentrate - per 1kg') &
    (df['date'] >= '2003-1') &
    (df['date']<= '2015-1') &
    (df['value'] > 0)
]
df_tomato_paste2.head()

,province,product_types,currency,product_group_id,product_line,value,date
92,KUYAVIA-POMERANIA,30% tomato concentrate - per 1kg,PLN,1,NaN,8.83,2010-1
243,SUBCARPATHIA,30% tomato concentrate - per 1kg,PLN,1,NaN,8.08,2006-4
368,WARMIA-MASURIA,30% tomato concentrate - per 1kg,PLN,1,NaN,5.46,2012-12
386,PODLASKIE,30% tomato concentrate - per 1kg,PLN,1,NaN,5.33,2006-1
557,SUBCARPATHIA,30% tomato concentrate - per 1kg,PLN,1,NaN,8.12,2007-5

In [53]:
df_tomato_paste2['value'].mean()

np.float64(46.3996886864085)