# Removing errors
Using the solutions from the previous class and the **product_prices_renamed.csv** file, modify `loc` so that it corrects the errors present in the dataset:

1. In the **date** column, data from 1888 appeared - '1888-0', change the value to 1999-1,
1. In the **date** column, data from 2099 appeared - '2099-13', change the value to 2019-1,
1. There is a spelling error in the **product_types** column - correct it. Number of pieces should be '10pcs.`. Check whether the task was done correctly.
1. Use `loc` to convert the values given in `EUR` to `PLN` with 4.15 exchange rate.
1. Filter from the set those rows where the price for the product is 3000.
Hint: Instead of writing `loc` twice, first query the data for rows where **currency** = `EUR` and save it to a variable.

> Remember that `loc` modifies data irrevocably.

In [61]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_renamed.csv',
    sep=';',
    encoding='UTF-8',
    decimal='.'
)

df

,province,product_types,currency,product_group_id,product_line,value,date
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3
...,...,...,...,...,...,...,...
149935,KUYAVIA-POMERANIA,NaN,PLN,2,pork meat (raw bacon) - per 1kg,12.15,2016-11
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3,NaN,0.00,2012-5
149937,LESSER POLAND,NaN,PLN,4,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6
149938,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11
149939,MASOVIA,NaN,PLN,4,Masurian barley groats - per 1kg,0.16,2005-10

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149940 entries, 0 to 149939
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   province          149940 non-null  object
 1   product_types     34272 non-null   object
 2   currency          149940 non-null  object
 3   product_group_id  149940 non-null  int64
 4   product_line      115668 non-null  object
 5   value             137088 non-null  float64
 6   date              149940 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 8.0+ MB

In [63]:
df.loc[df['date'] == '1888-0', 'date'] = '1999-1'
df.loc[df['date'] == '1888-0']

Empty DataFrame
Columns: [province, product_types, currency, product_group_id, product_line, value, date]
Index: []

In [64]:
df.loc[df['date'] == '2099-13', 'date'] = '2019-11'
df.loc[df['date'] == '2099-13']

Empty DataFrame
Columns: [province, product_types, currency, product_group_id, product_line, value, date]
Index: []

In [65]:
df['product_types'].unique()

array([nan, 'whole pickled cucumbers 0.9l - per 1pc.',
       'fresh chichen egges - per 666pcs.',
       '30% tomato concentrate - per 1kg',
       'frozen carrot and pea mix - per 1kg',
       'beet sugar white, bagged - per 1kg',
       'apple juice, boxed - per 1l', 'white table salt bagged - per 1kg',
       'natural chocolate plain - per 1kg'], dtype=object)

In [66]:
df.loc[df['product_types'] == 'fresh chichen egges - per 666pcs.', 'product_types'] = 'fresh chicken eggs - per 10pcs.'
df['product_types'].unique()

array([nan, 'whole pickled cucumbers 0.9l - per 1pc.',
       'fresh chicken eggs - per 10pcs.',
       '30% tomato concentrate - per 1kg',
       'frozen carrot and pea mix - per 1kg',
       'beet sugar white, bagged - per 1kg',
       'apple juice, boxed - per 1l', 'white table salt bagged - per 1kg',
       'natural chocolate plain - per 1kg'], dtype=object)

In [67]:

df['currency'].unique()

array(['PLN', 'EUR'], dtype=object)

In [68]:
df.loc[df['value'] <3000]
currency_eur = df['currency'] == 'EUR'
df.loc[currency_eur, 'value']=df.loc[currency_eur, 'value'].apply(lambda v: v * 4.15)

In [69]:
df.loc['currency', 'value'] = 'PLN'

C:\Users\UrosVukmanovic\AppData\Local\Temp\ipykernel_16856\3674558538.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PLN' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc['currency', 'value'] = 'PLN'

In [70]:
df['currency'].unique

<bound method Series.unique of 0           PLN
1           PLN
2           PLN
3           PLN
4           PLN
           ...
149936      PLN
149937      PLN
149938      PLN
149939      PLN
currency    NaN
Name: currency, Length: 149941, dtype: object>

In [73]:
df.to_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_cleaned_1.csv',
    sep = ';',
    decimal = '.',
    index = False
)